### ISSUE TITLE
Doesnt work for newest VRChat update. Broken.

### ISSUE THREAD

**Issue by SquidNeko** [ImTiara/AvatarHider#4]
Doesnt work for newest VRChat update. Broken.

**Comment by ImTiara** [comment]
Hi, i have repaired it for the latest VRChat version and done some quick testing and it seems to work just fine, but i currently don't have time to do more detailed testing and therefor i have not released the update just yet.
I will probably release the update at the end of today.

**Comment by SquidNeko** [comment]
Its still not released?
